### ISSUE TITLE
server side code missed

### ISSUE THREAD

**Issue by mkozhukh** [sencha/extjs-grid-performance#9]
Can you please add a full server side code, so benchmark can be validated ?

**Comment by mkozhukh** [comment]
now I see that sources/assets folder is missed as well
is there any way how this test can be run locally ?

**Comment by trevorgithub** [comment]
To add to this, the start script looks like this:
`
"scripts": {
    "start": "babel-node --presets es2015 ./server/express.js"
  },
`

but running it (after first doing `npm install`), results in this:
`
$ npm start
> web-application@1.0.0 start C:\Users\user1\git\extjs-grid-performance
> babel-node --presets es2015 ./server/express.js
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'C:\Users\user1\git\extjs-grid-performance\server\express.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at Object.<anonymous> (C:\Users\user1\git\extjs-grid-performance\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
`

Some instructions for building and running the grid performance tests would be helpful
